# Generated by Django 6.0.7 on 2026-07-22 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_remove_site_unique_site_name_per_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['-created_at'], 'permissions': [('can_edit_site', 'Can edit any site')], 'verbose_name': 'Site', 'verbose_name_plural': 'Sites'},
        ),
    ]
