# Generated by Django 6.0.7 on 2026-07-24 05:19

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_alter_site_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='footer',
            field=models.FileField(blank=True, null=True, upload_to='sites/footer/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['html']), apps.core.validators.validate_file_size]),
        ),
        migrations.AddField(
            model_name='site',
            name='header',
            field=models.FileField(blank=True, null=True, upload_to='sites/header/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['html']), apps.core.validators.validate_file_size]),
        ),
    ]
