# Generated by Django 6.0.7 on 2026-07-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_site_footer_site_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
