# Generated by Django 6.0.7 on 2026-07-29 11:36

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_site_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='sites/thumbnails/', validators=[apps.core.validators.validate_thumbnail_image]),
        ),
        migrations.AlterField(
            model_name='site',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='sites/favicons/', validators=[apps.core.validators.validate_favicon_image]),
        ),
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='sites/logos/', validators=[apps.core.validators.validate_logo_image]),
        ),
    ]
