# Generated by Django 6.0.7 on 2026-07-29 11:36

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_site_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='sites/thumbnails/', validators=[apps.core.validators.ImageValidator(max_height=800, max_width=800, min_height=100, min_width=100)]),
        ),
        migrations.AlterField(
            model_name='site',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='sites/favicons/', validators=[apps.core.validators.ImageValidator(max_height=512, max_width=512, min_height=16, min_width=16)]),
        ),
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='sites/logos/', validators=[apps.core.validators.ImageValidator(max_height=1000, max_width=1000, min_height=50, min_width=50)]),
        ),
    ]
