# Generated by Django 6.0.7 on 2026-07-30 09:08

import apps.core.validators
import apps.sites.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0009_site_thumbnail_alter_site_favicon_alter_site_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to=apps.sites.models.SiteImageUploadTo('favicons'), validators=[apps.core.validators.ImageValidator(max_height=512, max_width=512, min_height=16, min_width=16)]),
        ),
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.sites.models.SiteImageUploadTo('logos'), validators=[apps.core.validators.ImageValidator(max_height=1000, max_width=1000, min_height=50, min_width=50)]),
        ),
        migrations.AlterField(
            model_name='site',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=apps.sites.models.SiteImageUploadTo('thumbnails'), validators=[apps.core.validators.ImageValidator(max_height=800, max_width=800, min_height=100, min_width=100)]),
        ),
        migrations.AlterField(
            model_name='site',
            name='url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
