# Generated by Django 6.0.7 on 2026-07-30 09:08

import apps.core.validators
import apps.sites.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0009_site_thumbnail_alter_site_favicon_alter_site_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to=apps.sites.models.SiteImageUploadTo('favicons'), validators=[apps.core.validators.validate_favicon_image]),
        ),
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.sites.models.SiteImageUploadTo('logos'), validators=[apps.core.validators.validate_logo_image]),
        ),
        migrations.AlterField(
            model_name='site',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=apps.sites.models.SiteImageUploadTo('thumbnails'), validators=[apps.core.validators.validate_thumbnail_image]),
        ),
        migrations.AlterField(
            model_name='site',
            name='url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
