# Generated by Django 6.0.7 on 2026-07-30 11:34

import apps.core.validators
import apps.sites.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_page_hero_image'),
        ('sites', '0010_alter_site_favicon_alter_site_logo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to=apps.sites.models.SiteImageUploadTo('favicons'), validators=[apps.core.validators.ImageValidator(max_height=1000, max_width=1000, min_height=16, min_width=16)]),
        ),
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.sites.models.SiteImageUploadTo('logos'), validators=[apps.core.validators.ImageValidator(max_height=2000, max_width=2000, min_height=100, min_width=100)]),
        ),
        migrations.AlterField(
            model_name='site',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=apps.sites.models.SiteImageUploadTo('thumbnails'), validators=[apps.core.validators.ImageValidator(max_height=1500, max_width=1500, min_height=150, min_width=150)]),
        ),
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=apps.sites.models.SiteImageUploadTo('images'), validators=[apps.core.validators.ImageValidator(max_height=6000, max_width=6000, min_height=20, min_width=20)])),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Size in bytes, cached at save time.', null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_images_created', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(blank=True, help_text='Optional. Leave empty for site-wide reusable images.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='pages.page')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sites.site')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_images_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Image',
                'verbose_name_plural': 'Site Images',
                'ordering': ['-created_at'],
            },
        ),
    ]
