# Generated by Django 6.0.7 on 2026-07-30 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0011_alter_site_favicon_alter_site_logo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteimage',
            old_name='caption',
            new_name='file_name',
        ),
    ]
