# Generated by Django 6.0.7 on 2026-07-31 12:51

import apps.core.validators
import apps.sites.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0012_rename_caption_siteimage_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='footer',
            field=models.FileField(blank=True, null=True, upload_to=apps.sites.models.SiteFileUploadTo('footer'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['html']), apps.core.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='site',
            name='header',
            field=models.FileField(blank=True, null=True, upload_to=apps.sites.models.SiteFileUploadTo('header'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['html']), apps.core.validators.validate_file_size]),
        ),
    ]
