# Generated by Django 6.0.7 on 2026-08-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0013_alter_site_footer_alter_site_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteimage',
            name='device',
            field=models.CharField(choices=[('desktop', 'Desktop'), ('tablet', 'Tablet'), ('mobile', 'Mobile')], default='desktop', max_length=20),
        ),
    ]
