# Generated by Django 6.0.7 on 2026-08-04 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0014_siteimage_device'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePublishVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('header_hash', models.CharField(max_length=256)),
                ('footer_hash', models.CharField(max_length=256)),
                ('page_hashes', models.JSONField(default=dict, help_text='Mapping of page slug to its content hash.')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_publish_versions', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_versions', to='sites.site')),
            ],
            options={
                'verbose_name': 'Site Publish Version',
                'verbose_name_plural': 'Site Publish Versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddField(
            model_name='site',
            name='current_published_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sites.sitepublishversion'),
        ),
        migrations.AddConstraint(
            model_name='sitepublishversion',
            constraint=models.UniqueConstraint(fields=('site', 'version_number'), name='unique_site_version_number'),
        ),
    ]
