# Generated by Django 6.0.7 on 2026-08-19 07:09

import apps.sites.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0015_sitepublishversion_site_current_published_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteimage',
            name='device',
        ),
        migrations.AddField(
            model_name='siteimage',
            name='image_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('hero', 'Hero'), ('thumbnail', 'Thumbnail'), ('favicon', 'Favicon'), ('logo', 'Logo')], default='regular', max_length=20),
        ),
        migrations.CreateModel(
            name='ImageVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_type', models.CharField(choices=[('mobile', 'Mobile'), ('laptop', 'Laptop'), ('desktop', 'Desktop')], max_length=10)),
                ('image', models.FileField(upload_to=apps.sites.models.upload_to_variant)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('format', models.CharField(max_length=10)),
                ('file_size', models.PositiveIntegerField(help_text='Size in bytes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='sites.siteimage')),
            ],
            options={
                'ordering': ['width'],
                'constraints': [models.UniqueConstraint(fields=('image_upload', 'variant_type'), name='unique_site_image_variant_type')],
            },
        ),
    ]
