# Generated by Django 6.0.7 on 2026-08-19 10:29

import apps.core.validators
import apps.sites.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0017_sitepublishversion_asset_hashes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='global_css',
            field=models.FileField(blank=True, null=True, upload_to=apps.sites.models.SiteFileUploadTo('css'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['css']), apps.core.validators.validate_file_size]),
        ),
    ]
