# Generated by Django 6.0.7 on 2026-07-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('landing', 'Landing Page'), ('blog', 'Blog Page')], default='standard', max_length=20),
        ),
    ]
