# Generated by Django 6.0.7 on 2026-07-29 11:36

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_page_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/hero/', validators=[apps.core.validators.ImageValidator(max_height=2500, max_kb=300, max_width=2500, min_height=400, min_width=400)]),
        ),
    ]
