# Generated by Django 6.0.7 on 2026-07-30 09:05

import apps.core.validators
import apps.pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_page_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.pages.models.PageImageUploadTo('hero'), validators=[apps.core.validators.ImageValidator(max_height=2500, max_width=2500, min_height=400, min_width=400)]),
        ),
    ]
