# Generated by Django 6.0.7 on 2026-07-30 11:34

import apps.core.validators
import apps.pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_page_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.pages.models.PageImageUploadTo('hero'), validators=[apps.core.validators.ImageValidator(max_height=2160, max_width=3840, min_height=600, min_width=1200)]),
        ),
    ]
