# Generated by Django 6.0.7 on 2026-07-31 12:51

import apps.core.validators
import apps.pages.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_page_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='css',
            field=models.FileField(blank=True, null=True, upload_to=apps.pages.models.PageFileUploadTo('css'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['css']), apps.core.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='page',
            name='html',
            field=models.FileField(blank=True, null=True, upload_to=apps.pages.models.PageFileUploadTo('html'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['html']), apps.core.validators.validate_file_size]),
        ),
    ]
