# Generated by Django 6.0.7 on 2026-08-03 09:19

import apps.core.validators
import apps.pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_page_css_alter_page_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.pages.models.PageImageUploadTo('hero'), validators=[apps.core.validators.ImageValidator(max_height=2160, max_width=3840, min_height=300, min_width=500)]),
        ),
    ]
